mqtt:
  host: mosquitto
  port: 1883

detectors:
  # compreface:
  #   url: http://compreface:8000
  #   key: 12345
  deepstack:
    url: http://deepstack:5005
    timeout: 30
  # codeproject:
  #   url: http://ai-server:32168

  topics:
    frigate: frigate/events
    matches: double-take/matches
    cameras: double-take/cameras

frigate:
  url: http://frigate:5000
